const AGES = [...new Array(51)].map((v, i) => i + 20);

const RELIGIONS = [
	{ label: "Hindu", value: "hindu" },
	{ label: "Muslim", value: "muslim" },
	{ label: "Christian", value: "Christian" },
	{ label: "Parsi", value: "parsi" },
	{ label: "Jain", value: "jain" },
	{ label: "Buddhist", value: "buddhist" },
	{ label: "Jewish", value: "jewish" },
	{ label: "Spritiual", value: "spritiual" },
	{ label: "No Religion", value: "noreligion" },
	{ label: "Other", value: "other" },
];

const MOTHER_TONGUES = [
	{ label: "Select", value: "Select" },
	{ label: "Hindi", value: "Hindi" },
	{ label: "Marathi", value: "Marathi" },
	{ label: "Punjabi", value: "Punjabi" },
	{ label: "Bengali", value: "Bengali" },
	{ label: "Gujarati", value: "Gujarati" },
	{ label: "Urdu", value: "Urdu" },
	{ label: "Telugu", value: "Telugu" },
	{ label: "Kannada", value: "Kannada" },
	{ label: "English", value: "English" },
	{ label: "Tamil", value: "Tamil" },
	{ label: "Oriya", value: "Oriya" },
	{ label: "Marwari", value: "Marwari" },
	{ label: "Aka", value: "Aka" },
	{ label: "Arabic", value: "Arabic" },
	{ label: "Arunachali", value: "Arunachali" },
	{ label: "Assamese", value: "Assamese" },
	{ label: "Awadhi", value: "Awadhi" },
	{ label: "Baluchi", value: "Baluchi" },
	{ label: "Bengali", value: "Bengali" },
	{ label: "Bhojpuri", value: "Bhojpuri" },
	{ label: "Bhutia", value: "Bhutia" },
	{ label: "Brahui", value: "Brahui" },
	{ label: "Brij", value: "Brij" },
	{ label: "Burmese", value: "Burmese" },
	{ label: "Chattisgarhi", value: "Chattisgarhi" },
	{ label: "Chinese", value: "Chinese" },
	{ label: "Coorgi", value: "Coorgi" },
	{ label: "Dogri", value: "Dogri" },
	{ label: "English", value: "English" },
	{ label: "French", value: "French" },
	{ label: "Garhwali", value: "Garhwali" },
	{ label: "Garo", value: "Garo" },
	{ label: "Gujarati", value: "Gujarati" },
	{ label: "Haryanavi", value: "Haryanavi" },
	{ label: "Himachali/Pahari", value: "Himachali/Pahari" },
	{ label: "Hindi", value: "Hindi" },
	{ label: "Hindko", value: "Hindko" },
	{ label: "Kakbarak", value: "Kakbarak" },
	{ label: "Kanauji", value: "Kanauji" },
	{ label: "Kannada", value: "Kannada" },
	{ label: "Kashmiri", value: "Kashmiri" },
	{ label: "Khandesi", value: "Khandesi" },
	{ label: "Khasi", value: "Khasi" },
	{ label: "Konkani", value: "Konkani" },
	{ label: "Koshali", value: "Koshali" },
	{ label: "Kumaoni", value: "Kumaoni" },
	{ label: "Kutchi", value: "Kutchi" },
	{ label: "Ladakhi", value: "Ladakhi" },
	{ label: "Lepcha", value: "Lepcha" },
	{ label: "Magahi", value: "Magahi" },
	{ label: "Maithili", value: "Maithili" },
	{ label: "Malay", value: "Malay" },
	{ label: "Malayalam", value: "Malayalam" },
	{ label: "Manipuri", value: "Manipuri" },
	{ label: "Marathi", value: "Marathi" },
	{ label: "Marwari", value: "Marwari" },
	{ label: "Miji", value: "Miji" },
	{ label: "Mizo", value: "Mizo" },
	{ label: "Monpa", value: "Monpa" },
	{ label: "Nepali", value: "Nepali" },
	{ label: "Odia", value: "Odia" },
	{ label: "Pashto", value: "Pashto" },
	{ label: "Persian", value: "Persian" },
	{ label: "Punjabi", value: "Punjabi" },
	{ label: "Rajasthani", value: "Rajasthani" },
	{ label: "Russian", value: "Russian" },
	{ label: "Sanskrit", value: "Sanskrit" },
	{ label: "Santhali", value: "Santhali" },
	{ label: "Seraiki", value: "Seraiki" },
	{ label: "Sindhi", value: "Sindhi" },
	{ label: "Sinhala", value: "Sinhala" },
	{ label: "Sourashtra", value: "Sourashtra" },
	{ label: "Spanish", value: "Spanish" },
	{ label: "Swedish", value: "Swedish" },
	{ label: "Tagalog", value: "Tagalog" },
	{ label: "Tamil", value: "Tamil" },
	{ label: "Telugu", value: "Telugu" },
	{ label: "Tulu", value: "Tulu" },
	{ label: "Urdu", value: "Urdu" },
	{ label: "Other", value: "Other" },
];

const HEIGHTS = [
	{ label: "Select Height", value: "" },
	{ label: "Under 5 feet", value: 59 }, // 4 feet 11 inches = 59 inches
	{ label: "5 feet", value: 60 }, // 5 feet = 60 inches
	{ label: "5 feet 1 inch", value: 61 },
	{ label: "5 feet 2 inches", value: 62 },
	{ label: "5 feet 3 inches", value: 63 },
	{ label: "5 feet 4 inches", value: 64 },
	{ label: "5 feet 5 inches", value: 65 },
	{ label: "5 feet 6 inches", value: 66 },
	{ label: "5 feet 7 inches", value: 67 },
	{ label: "5 feet 8 inches", value: 68 },
	{ label: "5 feet 9 inches", value: 69 },
	{ label: "5 feet 10 inches", value: 70 },
	{ label: "5 feet 11 inches", value: 71 },
	{ label: "6 feet", value: 72 }, // 6 feet = 72 inches
	{ label: "6 feet 1 inch", value: 73 },
	{ label: "6 feet 2 inches", value: 74 },
	{ label: "6 feet 3 inches", value: 75 },
	{ label: "6 feet 4 inches", value: 76 },
	{ label: "6 feet 5 inches", value: 77 },
	{ label: "6 feet 6 inches", value: 78 },
	{ label: "6 feet 7 inches", value: 79 },
	{ label: "6 feet 8 inches", value: 80 },
	{ label: "6 feet 9 inches", value: 81 },
	{ label: "6 feet 10 inches", value: 82 },
	{ label: "6 feet 11 inches", value: 83 },
	{ label: "7 feet", value: 84 }, // 7 feet = 84 inches
	{ label: "Over 7 feet", value: 85 }, // For heights over 7 feet
];

const validData = {
	AGES,
	RELIGIONS,
	MOTHER_TONGUES,
	HEIGHTS,
};

export default validData;
